# April Code pudding Project (Youtube Sentiment Analysis)

## Importing Libraries

In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
  
import seaborn as sns
import re
import os

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from wordcloud import WordCloud

import xgboost as xgb
from textblob import TextBlob

from tqdm import tqdm

## Data Overview

In [55]:
dataset_path = os.path.join('..', 'datasets', 'archive')

comments = pd.read_csv(
    os.path.join(dataset_path, 'UScomments.csv'),
    on_bad_lines='skip',
    encoding='utf-8',
    low_memory=False
)
videos = pd.read_csv(
    os.path.join(dataset_path, 'USvideos.csv'), 
    on_bad_lines='skip', 
    encoding='utf-8')

In [56]:
comments = pd.read_csv(r'C:\Jeel Faldu\Data Scientist\Projects\april_code_jam_pudding\youtube_sentiment_analysis\datasets\archive\UScomments.csv', 
                       on_bad_lines='skip', 
                       encoding= 'utf-8', 
                       low_memory=False)

In [57]:
videos = pd.read_csv(r'C:\Jeel Faldu\Data Scientist\Projects\april_code_jam_pudding\youtube_sentiment_analysis\datasets\archive\USvideos.csv', 
                       on_bad_lines='skip', 
                       encoding= 'utf-8', 
                       low_memory=False)

In [58]:
display(comments.head(5)) # Display the first 5 rows of the comments DataFrame

,video_id,comment_text,likes,replies
0,XpVt6Z1Gjjo,Logan Paul it's yo big day ‼️‼️‼️,4,0
1,XpVt6Z1Gjjo,I've been following you from the start of your...,3,0
2,XpVt6Z1Gjjo,Say hi to Kong and maverick for me,3,0
3,XpVt6Z1Gjjo,MY FAN . attendance,3,0
4,XpVt6Z1Gjjo,trending 😉,3,0

In [59]:
display(videos.head(5)) # Display the first 5 rows of the videos DataFrame

,video_id,title,channel_title,category_id,tags,views,likes,dislikes,comment_total,thumbnail_link,date
0,XpVt6Z1Gjjo,1 YEAR OF VLOGGING -- HOW LOGAN PAUL CHANGED Y...,Logan Paul Vlogs,24,logan paul vlog|logan paul|logan|paul|olympics...,4394029,320053,5931,46245,https://i.ytimg.com/vi/XpVt6Z1Gjjo/default.jpg,13.09
1,K4wEI5zhHB0,iPhone X — Introducing iPhone X — Apple,Apple,28,Apple|iPhone 10|iPhone Ten|iPhone|Portrait Lig...,7860119,185853,26679,0,https://i.ytimg.com/vi/K4wEI5zhHB0/default.jpg,13.09
2,cLdxuaxaQwc,My Response,PewDiePie,22,[none],5845909,576597,39774,170708,https://i.ytimg.com/vi/cLdxuaxaQwc/default.jpg,13.09
3,WYYvHb03Eog,Apple iPhone X first look,The Verge,28,apple iphone x hands on|Apple iPhone X|iPhone ...,2642103,24975,4542,12829,https://i.ytimg.com/vi/WYYvHb03Eog/default.jpg,13.09
4,sjlHnJvXdQs,iPhone X (parody),jacksfilms,23,jacksfilms|parody|parodies|iphone|iphone x|iph...,1168130,96666,568,6666,https://i.ytimg.com/vi/sjlHnJvXdQs/default.jpg,13.09

In [60]:
comments.info() # Display information about the comments DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691400 entries, 0 to 691399
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   video_id      691400 non-null  object
 1   comment_text  691374 non-null  object
 2   likes         691400 non-null  object
 3   replies       691400 non-null  object
dtypes: object(4)
memory usage: 21.1+ MB

In [61]:
videos.info() # Display information about the videos DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7992 entries, 0 to 7991
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   video_id        7992 non-null   object
 1   title           7992 non-null   object
 2   channel_title   7992 non-null   object
 3   category_id     7992 non-null   int64
 4   tags            7992 non-null   object
 5   views           7992 non-null   int64
 6   likes           7992 non-null   int64
 7   dislikes        7992 non-null   int64
 8   comment_total   7992 non-null   int64
 9   thumbnail_link  7992 non-null   object
 10  date            7992 non-null   float64
dtypes: float64(1), int64(5), object(5)
memory usage: 686.9+ KB

In [62]:
comments.describe() # Display descriptive statistics of the comments DataFrame

           video_id comment_text   likes replies
count        691400       691374  691400  691400
unique         2266       434075    1060     369
top     XpVt6Z1Gjjo          Lol       0       0
freq            800          310  563752  649366

In [63]:
videos.info() # Display information about the videos DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7992 entries, 0 to 7991
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   video_id        7992 non-null   object
 1   title           7992 non-null   object
 2   channel_title   7992 non-null   object
 3   category_id     7992 non-null   int64
 4   tags            7992 non-null   object
 5   views           7992 non-null   int64
 6   likes           7992 non-null   int64
 7   dislikes        7992 non-null   int64
 8   comment_total   7992 non-null   int64
 9   thumbnail_link  7992 non-null   object
 10  date            7992 non-null   float64
dtypes: float64(1), int64(5), object(5)
memory usage: 686.9+ KB

In [64]:
comments.isna().sum() # Check for missing values in the comments DataFrame
comments.isna().sum()/len(comments) # Check for missing values in the comments DataFrame as a percentage

video_id        0.000000
comment_text    0.000038
likes           0.000000
replies         0.000000
dtype: float64

In [65]:
comments.dropna(subset=['comment_text'], inplace=True) # Drop rows with missing values in the 'comment_text' column

In [66]:
videos.isna().sum() # Check for missing values in the videos DataFrame

video_id          0
title             0
channel_title     0
category_id       0
tags              0
views             0
likes             0
dislikes          0
comment_total     0
thumbnail_link    0
date              0
dtype: int64

In [67]:
comments_duplicates = comments.duplicated().sum() # Check for duplicate rows in the comments DataFrame
display(comments_duplicates) # Display the number of duplicate rows in the comments DataFrame

219743

In [72]:
duplicated_comments = comments[comments['comment_text'].duplicated(keep=False)]
display(duplicated_comments) # Display the number of duplicate comments in the comments DataFrame

,video_id,comment_text,likes,replies
45,XpVt6Z1Gjjo,"This looks like a great video, but after you a...",0,0
76,XpVt6Z1Gjjo,Pls subscribe to my channel,0,0
81,XpVt6Z1Gjjo,M,0,0
156,cLdxuaxaQwc,Power is the disease. Care is the cure. Keep...,0,0
181,cLdxuaxaQwc,https://youtu.be/XBJtNAhVLag,0,0
...,...,...,...,...
691394,EoejGgUNmVU,Amazing!!!!!💚🌹💕🔥,2,0
691395,EoejGgUNmVU,Лучшая,1,0
691396,EoejGgUNmVU,qu'est ce que j'aimerais que tu viennes à Roan...,0,0
691397,EoejGgUNmVU,Ven a mexico! 😍 te amo LP,0,0
691399,EoejGgUNmVU,Kocham tą piosenkę😍❤❤❤byłam zakochana po uszy ...,0,0

In [69]:
videos_duplicates = videos.duplicated().sum() # Check for duplicate rows in the comments DataFrame
display(videos_duplicates) # Display the number of duplicate rows in the comments DataFrame

0